# This is a basic workflow that is manually triggered

name: github pages

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.6'
      - run:  mdbook build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: &{{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
